#!/bin/bash
# Initialize conversation knowledge base

set -e

KNOWLEDGE_DIR="/root/hiclaw-fs/shared/knowledge/conversations"
TOPICS_DIR="$KNOWLEDGE_DIR/topics"
SESSIONS_DIR="$KNOWLEDGE_DIR/sessions"
EXPORTS_DIR="$KNOWLEDGE_DIR/exports"
INDEX_FILE="$KNOWLEDGE_DIR/index.json"

echo "📚 Initializing conversation knowledge base..."

# Create directories
mkdir -p "$TOPICS_DIR" "$SESSIONS_DIR" "$EXPORTS_DIR"

# Initialize index.json if not exists
if [ ! -f "$INDEX_FILE" ]; then
  cat > "$INDEX_FILE" << 'EOF'
{
  "topics": [],
  "total_entries": 0,
  "updated_at": null
}
EOF
  echo "✅ Created index.json"
else
  echo "ℹ️  index.json already exists"
fi

# Create today's session file
TODAY=$(date +%Y-%m-%d)
SESSION_FILE="$SESSIONS_DIR/$TODAY.md"
if [ ! -f "$SESSION_FILE" ]; then
  cat > "$SESSION_FILE" << EOF
# $TODAY Conversations

<!-- Auto-generated by conversation-knowledge skill -->

EOF
  echo "✅ Created session file: $TODAY.md"
else
  echo "ℹ️  Session file for $TODAY already exists"
fi

echo ""
echo "📁 Knowledge base structure:"
echo "   $KNOWLEDGE_DIR/"
echo "   ├── index.json          # Topic index"
echo "   ├── topics/             # Topic-specific logs"
echo "   ├── sessions/           # Daily transcripts"
echo "   └── exports/            # Generated summaries"
echo ""
echo "✅ Knowledge base initialized successfully!"
