#!/bin/bash
# Record a conversation entry

set -e

KNOWLEDGE_DIR="/root/hiclaw-fs/shared/knowledge/conversations"
INDEX_FILE="$KNOWLEDGE_DIR/index.json"
TOPICS_DIR="$KNOWLEDGE_DIR/topics"
SESSIONS_DIR="$KNOWLEDGE_DIR/sessions"

# Parse arguments
TOPIC=""
SUMMARY=""
CHANNEL="unknown"
SESSION_KEY=""
KEYPOINTS=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --topic) TOPIC="$2"; shift 2 ;;
    --summary) SUMMARY="$2"; shift 2 ;;
    --channel) CHANNEL="$2"; shift 2 ;;
    --session-key) SESSION_KEY="$2"; shift 2 ;;
    --keypoints) KEYPOINTS="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Validate required fields
if [ -z "$TOPIC" ]; then
  echo "❌ Error: --topic is required"
  exit 1
fi

if [ -z "$SUMMARY" ]; then
  echo "❌ Error: --summary is required"
  exit 1
fi

# Generate slug from topic name
SLUG=$(echo "$TOPIC" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9\u4e00-\u9fa5]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//')

# Get current timestamp
TIMESTAMP=$(date +%Y-%m-%d\ %H:%M)
ISO_TIMESTAMP=$(date -Iseconds)
TODAY=$(date +%Y-%m-%d)

echo "📝 Recording conversation..."
echo "   Topic: $TOPIC"
echo "   Summary: $SUMMARY"
echo "   Channel: $CHANNEL"
echo "   Time: $TIMESTAMP"

# Ensure directories exist
mkdir -p "$TOPICS_DIR" "$SESSIONS_DIR"

# Create or update topic file
TOPIC_FILE="$TOPICS_DIR/$SLUG.md"
if [ ! -f "$TOPIC_FILE" ]; then
  cat > "$TOPIC_FILE" << EOF
# $TOPIC

<!-- Auto-generated by conversation-knowledge skill -->

EOF
  echo "✅ Created new topic file: $SLUG.md"
fi

# Append entry to topic file
cat >> "$TOPIC_FILE" << EOF

## $TIMESTAMP ($CHANNEL)

**摘要**: $SUMMARY

EOF

if [ -n "$KEYPOINTS" ]; then
  cat >> "$TOPIC_FILE" << EOF
**关键点**:
$KEYPOINTS

EOF
fi

# Add link to session transcript if session-key provided
if [ -n "$SESSION_KEY" ]; then
  echo "[[完整会话]](../sessions/$TODAY.md#$SESSION_KEY)" >> "$TOPIC_FILE"
fi

# Update index.json
# This is a simplified update - in production, use jq for proper JSON manipulation
if command -v jq &> /dev/null; then
  # Check if topic exists in index
  TOPIC_EXISTS=$(jq -r ".topics[] | select(.slug == \"$SLUG\") | .slug" "$INDEX_FILE" 2>/dev/null || echo "")
  
  if [ -z "$TOPIC_EXISTS" ]; then
    # Add new topic to index
    jq --arg slug "$SLUG" \
       --arg name "$TOPIC" \
       --arg ts "$ISO_TIMESTAMP" \
       --arg ch "$CHANNEL" \
       '.topics += [{"slug": $slug, "name": $name, "entry_count": 1, "first_recorded": $ts, "last_updated": $ts, "channels": [$ch], "tags": []}] | .total_entries += 1 | .updated_at = $ts' \
       "$INDEX_FILE" > "$INDEX_FILE.tmp" && mv "$INDEX_FILE.tmp" "$INDEX_FILE"
    echo "✅ Added topic to index"
  else
    # Update existing topic
    jq --arg slug "$SLUG" \
       --arg ts "$ISO_TIMESTAMP" \
       --arg ch "$CHANNEL" \
       '.topics = [.topics[] | if .slug == $slug then .entry_count += 1 | .last_updated = $ts | .channels = (.channels + [$ch] | unique) else . end] | .total_entries += 1 | .updated_at = $ts' \
       "$INDEX_FILE" > "$INDEX_FILE.tmp" && mv "$INDEX_FILE.tmp" "$INDEX_FILE"
    echo "✅ Updated topic in index"
  fi
else
  echo "⚠️  jq not found, skipping index update (install jq for full functionality)"
fi

# Append to daily session file
SESSION_FILE="$SESSIONS_DIR/$TODAY.md"
if [ ! -f "$SESSION_FILE" ]; then
  cat > "$SESSION_FILE" << EOF
# $TODAY Conversations

<!-- Auto-generated by conversation-knowledge skill -->

EOF
fi

cat >> "$SESSION_FILE" << EOF

---

## $TIMESTAMP ($CHANNEL) - $TOPIC

**摘要**: $SUMMARY

EOF

echo ""
echo "✅ Conversation recorded successfully!"
echo "   Topic file: $TOPIC_FILE"
echo "   Session file: $SESSION_FILE"

# Additional command: list recent
if [ "$1" = "--list-recent" ]; then
  echo "📋 Recent conversations will be handled by list-recent.sh"
fi
